### ISSUE TITLE
Error running against repo on github

### ISSUE THREAD

**Issue by gelias** [guilhermeslacerda/drtools-metric#1]
Steps ...

1) git clone https://github.com/gelias/ssl-pinning-java.git

2) drtools-metric.sh /Users/gelias/workspace/java-2019/ssl-pinning/ -a --console

Error:
------------------
SUMMARY OF METRICS
------------------
            Total of Namespaces: 0
                 Total of Types: 0Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:61)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0
	at structures.results.NamespaceMetricResult.getMedianOfTypes(NamespaceMetricResult.java:125)
	at output.MetricResultConsole.showSummary(MetricResultConsole.java:81)
	at output.MetricResultConsole.show(MetricResultConsole.java:94)
	at general.options.AllMetricsOption.execute(AllMetricsOption.java:11)
	at general.ProjectInfo.show(ProjectInfo.java:59)
	at main.Bootstrapper.analyzeAndShow(Bootstrapper.java:51)
	at main.Bootstrapper.runApp(Bootstrapper.java:36)
	at main.Bootstrapper.main(Bootstrapper.java:26)
	... 5 more

**Comment by guilhermeslacerda** [comment]
This problem happened because project doesn't have explicit reference to packages/namespaces.
In the new version of drtools-metric (1.6.0), this problem has been fixed.
